/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent.of.code.day1;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.junit.jupiter.api.Test;

import advent.of.code.DayTest;

class Day1Test extends DayTest {

	final Day1CalorieCounting day = new Day1CalorieCounting();

	@Test
	void testParseInput() {
		assertThat(day.parseInput(getInputPath()))
			.containsExactly(
				new Elf(List.of(1000, 2000, 3000)),
				new Elf(List.of(4000)),
				new Elf(List.of(5000, 6000)),
				new Elf(List.of(7000, 8000, 9000)),
				new Elf(List.of(10000))
			);
	}

	@Test
	void testMostCalorificElf() {
		assertThat(day.totalCaloriesOfMostCalorificElf(getInputPath())).isEqualTo(24000);
	}

	@Test
	public void testTopThreeElves() {
		assertThat(day.totalCaloriesOfTopThreeMostCalorificElves(getInputPath())).isEqualTo(45000);
	}
}
