/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent.of.code.day1;

import static org.assertj.core.api.Assertions.assertThat;

import java.net.URISyntaxException;
import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class Day1Test {

	final Day1CalorieCounting day = new Day1CalorieCounting();
	Path inputPath;

	@BeforeEach
	void setup() throws URISyntaxException {
		inputPath = Path.of(Day1Test.class.getResource("input-test.txt").toURI()).toAbsolutePath();
	}

	@Test
	void testParseInput() {
		assertThat(day.parseInput(inputPath))
			.containsExactly(
				new Elf(List.of(1000, 2000, 3000)),
				new Elf(List.of(4000)),
				new Elf(List.of(5000, 6000)),
				new Elf(List.of(7000, 8000, 9000)),
				new Elf(List.of(10000))
			);
	}

	@Test
	void testMostCalorificElf() {
		assertThat(day.totalCaloriesOfMostCalorificElf(inputPath)).isEqualTo(24000);
	}

	@Test
	public void testTopThreeElves() {
		assertThat(day.totalCaloriesOfTopThreeMostCalorificElves(inputPath)).isEqualTo(45000);
	}
}
